# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jhol < Formula
  desc "CLI to display and check Japanese holidays."
  homepage "https://github.com/winebarrel/jhol"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/jhol/releases/download/v1.1.0/jhol_1.1.0_darwin_amd64.tar.gz"
      sha256 "be44bc0d5359d886288b14f2aad663d23287ac7ee5d7b7a5e6f7f14575a5adef"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/jhol/releases/download/v1.1.0/jhol_1.1.0_darwin_arm64.tar.gz"
      sha256 "42ccd14bf5275356229e3d8279a1bc53db2f146b381de196db7a9baed6a6ff10"

      def install
        bin.install 'jhol'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/jhol/releases/download/v1.1.0/jhol_1.1.0_linux_arm64.tar.gz"
      sha256 "5a78a17e57ffb2664e3b37bdaca13ec7d181a755b76af85989cf94cbd208dcfe"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/jhol/releases/download/v1.1.0/jhol_1.1.0_linux_amd64.tar.gz"
      sha256 "2d7053b30a5068bb89f19c7c1fbee55d5c44faa311d728212bf9ec50adf3ab36"

      def install
        bin.install 'jhol'
      end
    end
  end
end
