# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jhol < Formula
  desc "CLI to display and check Japanese holidays."
  homepage "https://github.com/winebarrel/jhol"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.1/jhol_1.0.1_darwin_amd64.tar.gz"
      sha256 "a101ce060a0a9debb8e006d398df28534bdb0080e2fcdbb82577c28352fb825a"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.1/jhol_1.0.1_darwin_arm64.tar.gz"
      sha256 "34d9fa7a6b687ad50c8a4b87a3dfb2979555ca92d747da4e38748d2c7d5ceab3"

      def install
        bin.install 'jhol'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.1/jhol_1.0.1_linux_arm64.tar.gz"
      sha256 "5cbf6ef9f4b40c6bf33b926e327418724f10996c1a567818fe17b67ce745dba5"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.1/jhol_1.0.1_linux_amd64.tar.gz"
      sha256 "317cf670c3046ad37e6c5af281cbd07b0154b21eaa5ea7d3770a1b2692f2f6b2"

      def install
        bin.install 'jhol'
      end
    end
  end
end
