# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jhol < Formula
  desc "CLI to display and check Japanese holidays."
  homepage "https://github.com/winebarrel/jhol"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.0/jhol_1.0.0_darwin_amd64.tar.gz"
      sha256 "58fbd2688a5529d2fa5e8a316d4fb9c3815723454447b666ab2c551a3800792a"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.0/jhol_1.0.0_darwin_arm64.tar.gz"
      sha256 "43aadb1ff8fd8190e9c690096a69e45ea55849039bb779664518ca2abbe3bf83"

      def install
        bin.install 'jhol'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.0/jhol_1.0.0_linux_arm64.tar.gz"
      sha256 "a64066080fee8b890543c0356a5323647fe79d6c2f0ff7381fafba2294f5167b"

      def install
        bin.install 'jhol'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/jhol/releases/download/v1.0.0/jhol_1.0.0_linux_amd64.tar.gz"
      sha256 "8bdf5481961c3c76ef00fe83a1f37065c83557a365f1f7dc74138ea852c06268"

      def install
        bin.install 'jhol'
      end
    end
  end
end
